<?php 
/************************************************************************/
/* AChecker                                                             */
/************************************************************************/
/* Copyright (c) 2008 - 2011                                            */
/* Inclusive Design Institute                                           */
/*                                                                      */
/* This program is free software. You can redistribute it and/or        */
/* modify it under the terms of the GNU General Public License          */
/* as published by the Free Software Foundation.                        */
/************************************************************************/
/* This file was generated by the AChecker 1.4 installation script.     */
/* File generated 2014-01-16 10:01:34                                   */
/************************************************************************/
/************************************************************************/
/* the database user name                                               */
define('DB_USER',                      'root');

/* the database password                                                */
define('DB_PASSWORD',                  '');

/* the database host                                                    */
define('DB_HOST',                      'localhost');

/* the database tcp/ip port                                             */
define('DB_PORT',                      '3306');

/* the database name                                                    */
define('DB_NAME',                      '');

/* The prefix to add to table names to avoid conflicts with existing    */
/* tables. Default: AC_                                                 */
define('TABLE_PREFIX',                 '');

/* Where the temporary files are located.  This includes all file       */
/* manager and imported files.  If security is a concern, it is         */
/* recommended that the temporary directory be moved outside of the web	*/
/* accessible area.														*/
define('AC_TEMP_DIR', '/tmp/');

/* DO NOT ALTER THIS LAST LINE                                          */
define('AC_INSTALL', TRUE);

$_pages = array(
    'page/credits.php' => array(
        'title_var' => 'credits',
        'parent' => AC_NAV_TOP,
    ),
    'page/about.php' => array(
        'title_var' => 'about',
        'parent'=>AC_NAV_TOP,
    ),
);
